### ISSUE TITLE
More then one type of event

### ISSUE THREAD

**Issue by atambo** [elevation/event_calendar#12]
You could make it easy to have more then one type of event by make the following changes:

in app/helpers/calendar_helper.rb use event.class.to_s.downcase.pluralize instead of hardcoding the name of the model name

and in vendor/plugins/event_calendar/lib/event_calendar/calendar_helper.rb make the event_id be event_modelname_id so the hover highlight will not highlight events from different models by using event.class.to_s.downcase

**Comment by stevenhaddox** [comment]
+1. I'm using this on my own model as well, but didn't have the time available to fork it and fix it due to a tight deadline and just came across this.  I merely created a before_validation callback that assigned my start_at and end_at dynamically even though it's slightly duplicate data.  A simple refactor could adjust the model to the new fields, but again, tight deadline :(

**Comment by dshimy** [comment]
I just sent a pull request for this one.

**Comment by jeffschuil** [comment]
Better handle events of different classes. Minor changes to dshimy&#39;s commit. Closed by 80b0046cc048d0f5c59b5865f6e6856878d4ea8a.
