### ISSUE TITLE
Performance issues for many events/day

### ISSUE THREAD

**Issue by kbighorse** [elevation/event_calendar#21]
My use case has up to 20 events/day and increasing.  I notice that cycling back in time by month takes a lot of time to load the page.  I understand it's doing a lot of logic per day, but it is currently crashing Chrome and is choking Safari noticeably.  Anything I can do to improve this?

Kimball

**Comment by jeffschuil** [comment]
I'm sure there are ways to improve performance. 20+ events per day is certainly more than I've ever had to deal with in the plugin, and I can see how it would start to bog down.

I would start by looking at the mysql queries. There are various Rails plugins that can help you do this. (I like to use the rails-footnotes plugin.) For instance, if you happen to be loading data from associated tables for each event, perhaps you could use eager loading. Otherwise the main sql statement is just selecting all the events in a date range. Something like this:

SELECT \* FROM events WHERE (('2010-08-01 07:00:00' <= end_at) AND (start_at < '2010-09-05 07:00:00')) ORDER BY start_at ASC

The next thing I would look at is caching, with page caching being the best. The hard part is invalidating the cache when there are updates to your calendar, but you could go the easy route and just delete the whole calendar cache directory.

Let me know how it goes.
Jeff

**Comment by kbighorse** [comment]
Cool, I'll shelve this for now and look in to building it out in the future.

Kimball
